### ISSUE TITLE
}bedrock.dim.import errors when the alias change element

### ISSUE THREAD

**Issue by AdamxDavis** [cubewise-code/bedrock#109]
**Describe the bug**

If the alias value for an element changes over time the process will report an ambiguous element and the process will error. 

**To Reproduce**

Steps to reproduce the behaviour:
1. Clone a dimension with an alias using }bedrock.dim.export and import using }bedrock.dim.import.
2. In the source dimension change the alias from one element to another.
3. Clone a dimension with an alias using }bedrock.dim.export and import using }bedrock.dim.import. The }bedrock.dim.import process will fail. 

**Expected behaviour**

}bedrock.dim.import should detect that the alias value to be loaded will be ambiguous. The process should remove the offending alias value from the target dimension. Then load the alias value against the new element

**Screenshots**
[TM1ProcessError_20191018190438_87225808_}bedrock.hier.import.log

**Version**
 - PA 2.0.9

**Additional context**

**Comment by lotsaram** [comment]
Hi @AdamxDavis  
Hate to say it again but _did you test on the latest version?_ The current version of the hier.import process has this code on the data tab which tests for the type of the attribute and if "AA" then includes the enforce unique flag in the AttrPutS. So there should be no error, only that in such a case the alias that gets stored would have the principal name appended at the snd of the string.  
![image](https://user-images.githubusercontent.com/29408388/67180655-83bafa80-f3da-11e9-8e14-469bb91a41d0.png)

As to whether the process should automatically detect conflict in alias versus alias principal name of another element, I think this is more of a philosophical question. If it's an alias<->alias conflict which alias should win? With hierarches it is also more tricky to detect as you could still get a ElementIndex returning 0 and have a conflict since there can't be any conflict with leaf names even though the leaf may not exist in the hierarchy. I think this is more of a GIGO issue and handling with the unique flag and thus avoiding any error should be sufficient.

Please test with the latest hier.import process and confirm that this runs without error in this case.

**Comment by lotsaram** [comment]
Hi @AdamxDavis have you had a chance to look at this?
