### ISSUE TITLE
}bedrock.cube.data.clear can not save, run

### ISSUE THREAD

**Issue by lingowang** [cubewise-code/bedrock#168]
**Describe the bug**
it seems this **}bedrock.cube.data.clear** doesn't work at all, with the latest 4.1.1 package. cannot even save the TI. However, using Notepad ++ to check the original .pro file, it seems the Prolog script IS completed. see the screens below.

**To Reproduce**
1. copy all }bedrock 4.1.1 TI to an empty folder, then start the DB
2. Open the TI, then re-save it
3. Error: Prolog procedure line (472): END or ENDIF statement missing.
        sRandomInt      = NumberToString( INT( RAND( ) * 1000 ));

**Expected behavior**
Would think we can copy the .pro files to a db folder.

**Version**
 - OS: [e.g. Windows Server 2106]
  - TM1 Server Version: [e.g. 11.7]

![image](https://user-images.githubusercontent.com/37170682/81974236-de0df800-9657-11ea-9ae9-7d2baa293be4.png)

![image](https://user-images.githubusercontent.com/37170682/81974250-e36b4280-9657-11ea-8cdf-41656a1a4418.png)

**Comment by lotsaram** [comment]
Just fixed @lingowang 
@4rtem this was due to #164 (I guess you did find/replace or something in Notepad++ or Sublime?? You didn't change the 572 property (code lines on prolog) so last 8 lines not read!) And I didn't pick this up in reviewing change as I assumed it had been done in Arc.
![image](https://user-images.githubusercontent.com/29408388/81978619-1566af80-962c-11ea-99f4-a7194c071a2b.png)
