### ISSUE TITLE
"ProcessBreak" return status in REST API considered "CompletedSuccessfully"

### ISSUE THREAD

**Issue by MariusWirtz** [cubewise-code/bedrock#186]
**Describe what you did so far.**
When you execute a bedrock process with illegal arguments, bedrock will often finish with the status `ProcessBreak`.

TM1py Example:
``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, ssl=True, user="admin", password="apple") as tm1:

    success, status, error_log_file = tm1.processes.execute_with_return(
        process_name="}bedrock.security.client.clone",
        pSrcClient="NotExisting",
        pTgtClient="Notexisting2")
``` 

This is what you find in the logs.
`92240   [14]   ERROR   2020-07-08 21:37:31.817   TM1.Process   Process "}bedrock.security.client.clone":  finished with ProcessBreak`

The problem is that the REST API translates the status "Finished with ProcessBreak" to "CompletedSuccessfully".
The above code would produce:
`True, "CompletedSuccessfully", None` in TM1py

So from TM1py, or REST in general, the failure is invisible!

**Describe what's not working the way you expect.**
Since most TM1 clients are now communicating with TM1 through REST, I think bedrock needs to abort in a way that is transparent through REST.
- If ItemReject is used, in REST we receive the status `CompletedWithMessages`
- If ProcessQuit is used, in REST we receive the status `QuitCalled`
- If the process actually aborts, we receive the status `Aborted`

**Version**
- TM1 Server Version: 11.7

**Comment by lotsaram** [comment]
Hi @MariusWirtz 

I would see this more as a bug in the Rest API that the thread status should return "ProcessFinishedWithBreak" as opposed to "CompletedSuccessfully". (Note: I think originally a process exiting via Break showed up same as major error status with Rest API. IT must be said the current situation is preferable as process exiting on break indicates the developer handling a potential error and deliberately exiting with break rather than error).  

Whether bedrock processes should error versus "fail silently" was deliberated extensively while planning for v4 and it was decided that bedrock should exit with ProcessError only in really exceptional circumstances. There's a lot of extra logging now directly to the message log which can be optionally switched on to assist with troubleshooting. It's a deliberate decision that bedrock doesn't error and writes a log instaid. So in terms of what you are asking is something like a new Boolean parameter pHardFail to all processes in the bedrock library. I think that's a lot of work, in all likelihood too much work for too little benefit.

**Comment by MariusWirtz** [comment]
Hi @lotsaram,

I agree. The preferred option would be that IBM returns a `ProcessFinishedWithBreak` return code through the API.

From am TM1py or REST side, it is irrelevant to me if the process failed because the developer designed it that way or if the process failed because of an unhandled error.
I must be able to know if the process succeeded or not after I executed it. 
Parsing the logs is not a real option because there is no unambiguous way to map the log entries against individual process executions.

I see your point about the refactoring effort. I think it's up to IBM.

**Comment by MariusWirtz** [comment]
@hubert-heijkers, 
Could you enlighten us, why the TM1 REST API considers `ProcessBreak` as `ExecutedSuccessfully`? 
Would it be possible to get a dedicated REST process return status for `ProcessBreak` in the next version of TM1?

**Comment by cubewise-tryan** [comment]
Hi @MariusWirtz  & @lotsaram,

I am not sure whether there should be a separate return value if you "break" out of a process. The break keyword in all programming languages that I can think means "I am done in the this code block", it doesn't mean there is an error. If arguments are invalid you would normally throw an argument exception.

**Comment by Hubert-Heijkers** [comment]
@MariusWirtz, ProcessBreak is documented as stopping the processing the source data and continuing to the Epilog portion of the process. This, as @cubewise-tryan suggests, is the same as breaking out of a loop in any programming language. If the intention was to terminate the process with an Error then either ProcessError or ProcessQuit can be used instead.

**Comment by MariusWirtz** [comment]
@Hubert-Heijkers,
thanks for your response on that one. It makes sense.

I think then the bedrock library should exit with a return status that is delegated through REST when the process does not succeed.
When calling bedrock from a script or application that interacts with TM1 through the REST API we have to know if the process succeeded or not.
