### ISSUE TITLE
Bedrock.Dim.AllConsols.Delete

### ISSUE THREAD

**Issue by jbeanz23** [cubewise-code/bedrock#19]
This process is hardcoded to pass in ' ' to pDelim of process }bedrock.hier.consol.delete which executes successfully but does not remove any consolidations.  If i run from }bedrock.hier.consol.delete with pDelim as the default & and pTemp as 0 (instead of current default 1) then the process does as expected and deletes consolidated elements.  There is no pTemp passed in from shell and delimiter is hardcoded to blank instead of &.

**Comment by lotsaram** [comment]
this is fixed @jbeanz23 
_pTemp_ wasn't relevant (actually the bedrock.hier.consol.delete process shouldn't have even had that parameter since for internal operations it isn't relevant)
The issue was that validation on _pDelim_ was too strict. If blank then the default value "&" should be used.
No change actually needed to the B3 shell process, only to the B4 process.
