### ISSUE TITLE
}bedrock.cube.data.import - Optional delete of file

### ISSUE THREAD

**Issue by scrumthing** [cubewise-code/bedrock#221]
When using }bedrock.cube.data.export and }bedrock.cube.data.import to copy data within a cube or between, it would be handy to have an optional parameter to delete the file after the import. Because it is only used due to feeders in the cube, thereis no need to persist that file. 

Alternativ approach:
New function }bedrock.cube.data.copyviacsv wher eimport and export are combined in Prolog and epilog and the file is deleted afterwards.

**Comment by lotsaram** [comment]
Hi @scrumthing,  
I'm not convinced that such a functionality should be included as a control parameter within bedrock library itself as this can already be achieved in other ways. For example if a process is calling cube.data.import then the calling process can do the file deletion after the import completes (since it must know the name of the file it passed to the import). Or if loading many source files in parallel then WildcardFileSearch could also be used to loop through all files matching a given string and delete them all (or just use the same wildcard and use ExecuteCommand and native OS script to do the file deletion).  
So as the same functionality can already be easily achieved what is the benefit to add this to the bedrock process itself?  
(On the other hand of course it is a quick, easy and more or less risk free addition).

**Comment by scrumthing** [comment]
Hi @lotsaram, 
I totally agree that it can be easily achieved otherwise. But it can easily be forgotten, too. Especially if you use bedrock to export and import the data in a single process. You just have to call two processes and you are done. Writing the snippet to delete the file takes up almost the same amount of time. 
We all forget to delete an export file from time to time. But if it is just changing one parameter in bedrock, it could improve data governance.
