### ISSUE TITLE
Handle invalid attribute types in dim.clone

### ISSUE THREAD

**Issue by psegal** [cubewise-code/bedrock#239]
**Describe what you did so far.**
I'm attempting to clone a dimension to an existing dimension using }bedrock.dim.clone process, latest version. 

**Describe what's not working the way you expect.**
Didn't get the expected result? Describe:
1. Expected the Dimension to be cloned to the existing dimension with attributes.
2. I'd like attributes to come across as well. 
3. Works OK  if I set the attribute parameter to 0 but not to 1.

**Version**
- OS: Windows server on cloud
- TM1 Server Version: 11.6.00006.2

**Additional context**
![image](https://user-images.githubusercontent.com/27949728/107653538-a9c47800-6c79-11eb-8e9d-77efd970c1f3.png)

**Comment by lotsaram** [comment]
Hi @psegal   
We use this process internally _all the time_ and don't see this issue. I suspect that the issue is something corrupt with the source dimension.  
I notice from your screenshot that the error message is  

`Undefined attribute type ""`  

When cloning the attributes I am pretty sure the code is expecting element types AA, AS or AN and then taking the second character for the AttrInsert in the target dimension. What I stringly suspect has happened is that the }ElementAttributes_Company dimension has been edited directly in Arc and contains elements with type "S" or "N". You won't notice this if browsing the }ElementAttributes cube or doing a CellGetS or DB directly to the attribute cube but a AttrS would fail as the attribute wouldn't be recognized as valid.  
The solution is that you need to delete and correctly recreate the attributes with invalid types. Can you please confirm if this is the case? Assuming it is this is something we shoudl probably handle in the code to let the user know the source dimension contains invalid attribute types.

**Comment by psegal** [comment]
Hi @lotsaram ,

Yes, that was it - an attribute with type of S. Does this mean Arc doesn't apply the correct type when creating a new attribute, or was it a glitch?

Thanks

Paul

**Comment by lotsaram** [comment]
Arc creates attributes with correct types when adding from the dimension editor for the source dimension. But I think what must have happened is that someone opened the }ElementAttributes dimension in the dimension editor and added a string element to the }ElementAttributes dimension.

**Comment by psegal** [comment]
OK, sounds likely. Can close this unless you want to keep it open to provide a specific error message. Thanks for the help.

**Comment by lotsaram** [comment]
Converting to ER.
The dim.clone process should handle the case where ElType in the }ElementAttribute dimension returns "S" or "N" due to elements being inserted incorrectly into the attribute dimension.
