### ISSUE TITLE
}bedrock.hier.unwind

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#240]
Following a topic on LinkedIn by Cristoph Hein, who was discussing the DNLEV function today, I was wondering why the function does not appear in the code. I would almost assume this function to be used, since if DNLEV = 1, no unwind needs to be done anyway. For those connected with Christoph, it is contribution "13/500 - DNLEV" as of Feb 17, 2021.

**Comment by lotsaram** [comment]
If DNLEV=1 then the dimension is perfectly flat and I agree no unwind needs to happen.

However, for a library like bedrock I wouldn't go further than that. Yes maybe with DNLEV=2 the hierarchy is quite flat but I wouldn't support arbitrarily skipping the unwind because of this. If the user requests the sunction to unwind a flat dimension or a specific rollup then that's what should happen.

**Comment by wimgielis** [comment]
Okay great.
I would also not go further than IF( DNLEV( ) = 1);
because anything above 1 will/can require an unwind.


------

Best regards / Beste groeten,

Wim Gielis
MS Excel MVP 2011-2014
https://www.wimgielis.com <http://www.wimgielis.be>


Op wo 17 feb. 2021 om 14:31 schreef lotsaram <notifications@github.com>:

**Comment by wimgielis** [comment]
Thanks




Op do 4 mrt. 2021 om 10:57 schreef lotsaram <notifications@github.com>:
