### ISSUE TITLE
}bedrock.cube.view.create

### ISSUE THREAD

**Issue by wimgielis** [cubewise-code/bedrock#292]
**Describe the bug**
When the cube name contains a % character, the process fails.

**Expected behavior**
The % character is allowed for cube names, so I would expect that this works.

**Version**
latest

**Additional context**
The reason will be in the use of Expand. That function is useful but can also lead to issues when variables/parameters contain the % character.

**Comment by lotsaram** [comment]
Honestly I think that’s an extreme edge case. Object names should never contain such characters. Especially now with rest API. Needing to escape characters is a real pain.

**Comment by wimgielis** [comment]
I can agree but not only the cubename is an issue.
Anytime an % is passed within for instance the view name (to create a view on a cube that does not have a % character) it also fails.

**Comment by lotsaram** [comment]
Hi @wimgielis 
As you note this is due to the extensive use of Expand() in bedrock to get variable names at runtime. There is no way to handle this as the server will expect any '%' within the string to expand to have both opening and closing %.
Although % in object names which are saved on the file system is _possible_ it is definately _**not advised and not good practice**_.  Such characters shouldn't be used in object names.
