### ISSUE TITLE
Intermediate file not deleted when using parameter pFile=1 for }bedrock.cube.data.copy and }bedrock.cube.data.copy.intercube

### ISSUE THREAD

**Issue by mepema** [cubewise-code/bedrock#360]
Setting parameter **pFile** to 1 when calling **}bedrock.cube.data.copy** and **}bedrock.cube.data.copy.intercube** uses a file to indirectly copy data and should then delete it afterwards.
However, it appears the file is not deleted and therefore the intermediate files could potentially clogg up the location they're created in.
The location for the intermediate files is designated by a dot ('.') which basically refers to the data folder of the instance.
It seems that the DEL command does not work with the dot notation. (Note that the issue was observed in Windows. The rm command in Linux may behave as expected)
Using a fully defined path as location - like the folder for the error logs - appears to solve the problem.

Code suggestion:
`## File location for indirect data copy`
`#cDir    = '.' | sOSDelim;`
`cDir    = GetProcessErrorFileDirectory;`

**Comment by lotsaram** [comment]
Hi @mepema I think this can also depend on whether the TM1 server is running as a service vs application with GUI and also whether any cd commands have been run in any previous command line execution called from the server.

I do agree though that using the logging directory for files rather than the data directory would solve this issue and is probably better practice not to be dumpign files into the data directory.

You are welcome to submit a pull request including this enhancement.
