### ISSUE TITLE
Question regarding }bedrock.cube.view.publish

### ISSUE THREAD

**Issue by hermie64** [cubewise-code/bedrock#46]
**Describe what you did so far.**
It's probably just me, but...
I execute process }bedrock.cube.view.publish and omitted parameter pCube.
The process nevertheless returns "Process completed successfully".
tm1server.log includes an error.

**Describe what's not working the way you expect.**
Didn't get the expected result? Describe:
1. I would expect error msg instead of "Process completed successfully".
2. NA

**Version**
- OS: Windows Server 2012 R2
- TM1 Server Version: PAL 2.0.7 

**Additional context**
NA

**Comment by lotsaram** [comment]
Hi @hermie64 

What you are describing sounds like expected behaviour. If there is a parameter validation error then bedrock will write to the message log what the error(s) is with LogOutput and will then call ProcessBreak. No work will be done. The process status will still be ProcessExitNormal / ProcessExitByBreak but without major error status. This is a standard feature of bedrock 4 and is different from bedrock 3.

The reason for this is to avoid rollbacks due to error status. As many of the processes (not this particular one) can perform work on multiple objects within one execution then this is important to avoid a rollback applying to the whole process when there is a (minor) validation error applying to only a small part of the overall work done by the process.
