### ISSUE TITLE
}bedrock.cube.view.create  not compatible with ViewCreate in advance.

### ISSUE THREAD

**Issue by AnthonyCool** [cubewise-code/bedrock#65]
**Describe the bug**
In bedrock 3, cube.view.create can be called after viewcreate(). Yet in bedrock 4, }cube.view.create will throw an minor error after viewcreate().

**Screenshots**
**Bedrock 3 runs successfully**
![image](https://user-images.githubusercontent.com/37695612/62280575-cd044980-b47e-11e9-91ee-c810fc94b74d.png)

**Bedrock 4 runs with minor error**
![image](https://user-images.githubusercontent.com/37695612/62280686-0046d880-b47f-11e9-87aa-93246eb3c830.png)

**The error message**
![image](https://user-images.githubusercontent.com/37695612/62280740-181e5c80-b47f-11e9-8aeb-fad58466127d.png)

**The error message**
![image](https://user-images.githubusercontent.com/37695612/62280803-32f0d100-b47f-11e9-87d3-155d7ba21f52.png)

**Without viewcreate() in advance, bedrock 4 runs successfully**
![image](https://user-images.githubusercontent.com/37695612/62280652-ec9b7200-b47e-11e9-9d7a-4b539ba357e5.png)

**Comment by AnthonyCool** [comment]
@lotsaram Hi man, thanks for your notice. May I ask if it is a bug?

**Comment by lotsaram** [comment]
Hi @AnthonyCool yes I agree it's a bug. The behaviour should be the same as bedrock 3. If the view already exists it should be modified and not cause an error.

**Comment by lotsaram** [comment]
Hi @AnthonyCool I investigated this and eventually was able to replicate. But it isn't a bug (except in how you are creating the view or calling the process ... one or the other).

You get the error because you do the ViewCreate with AsTemporary=FALSE but then you call }bedrock.cube.view.create with AsTemporary=TRUE

You can't assign a temp subset to a permanent view which is why you get the error.

We can test for ViewExists and SubsetExists but there is no way in TI to return if the object is temp or permanent so there is no way to trap this.

You need to add *AsTemporary* when doing the ViewCreate, or otherwise make sure this value is **consistent**. Or else just remove the pre ViewCreate in this instance since it serves no purpose.

Closing this issue.
