### ISSUE TITLE
Bedrock.cube.dimension.add (option to keep data results in error)

### ISSUE THREAD

**Issue by JDLovering** [cubewise-code/bedrock#80]
**Describe the bug**
ERROR when trying to add dimension with TI }bedrock.cube.dimension.add

**To Reproduce**
1. Go to process 'TI }bedrock.cube.dimension.add'

2. Run with parameters see screenshot below.
![screenshot3 1](https://user-images.githubusercontent.com/39148628/63328464-c91f6500-c362-11e9-87af-de376a84d7a1.png)

3. Result is the process stalls once clone cube created. 
_"}bedrock.cube.data.copy.intercube":  Error on line 992
Syntax error on or before: "
( cThisProcName, 'pL
 equal sign not found " : Could not initialize process_
**Expected behavior**
Expected the dimension to be added to the cube at position 1 with data
**Screenshots**

After run clone left and dimension not added

![screenshot4](https://user-images.githubusercontent.com/39148628/63328135-2cf55e00-c362-11e9-81a7-3bb79e778488.PNG)

**Version**
 -  OS: Windows 10 Ed
  - TM1 Server Version: 11.2

**Additional context**

Local instance of TM1 running in Bootcamp

**Comment by lotsaram** [comment]
Hi @JDLovering 
As stated the minimum supported version is 11.4 and you are using 11.2. The error is due to the RunProcess function at line 992 of prolog in cube.data.copy.intercube. The function isn't recognized by 11.2 server so it assumes it is a variable.

You could do a local patch of replacing RunProcess with ExecuteProcess but I would recommend upgrading to the most recent PAL, the latest public release is up to 11.6 now.
